import Link from "next/link";
import { notFound } from "next/navigation";
import { supabaseAdmin } from "../../../lib/supabase/admin";
export const dynamic = "force-dynamic";
export const metadata = { title: "Order confirmation", description: "View your Sara Masala order status.", alternates: { canonical: null }, robots: { index: false, follow: false }, referrer: "no-referrer" as const };
export default async function Confirmation({ params, searchParams }: { params: Promise<{ orderNumber: string }>; searchParams: Promise<{ token?: string }> }) {
  const { orderNumber } = await params; const { token } = await searchParams;
  if (!token || !/^[a-f0-9-]{36}$/i.test(token)) notFound();
  const { data: order } = await supabaseAdmin().from("orders").select("order_number,customer_name,shipping_address,status,payment_status,subtotal,shipping,discount,total,order_items(product_name,weight,quantity,unit_price,line_total)").eq("order_number", orderNumber).eq("confirmation_token", token).single();
  if (!order) notFound(); const a = order.shipping_address;
  const steps = [["confirmed", "Confirmed"], ["packed", "Packed"], ["shipped", "Shipped"], ["out_for_delivery", "Out for delivery"], ["delivered", "Delivered"]] as const;
  const currentIndex = steps.findIndex(([status]) => status === order.status); const support = process.env.CUSTOMER_SUPPORT_EMAIL || "hello@saramasala.in";
  const invoiceUrl = `/api/orders/${encodeURIComponent(order.order_number)}/invoice?token=${encodeURIComponent(token)}`;
  return <main className="content-page confirmation"><p className="eyebrow">{order.payment_status === "paid" ? "ORDER CONFIRMED" : "ORDER STATUS"}</p><h1>Thank you,<br /><em>{order.customer_name}.</em></h1><p>Order {order.order_number}</p><p>Payment: <strong>{order.payment_status}</strong> · Order: <strong>{order.status.replaceAll("_", " ")}</strong></p>{order.status === "cancelled" && <p className="confirmation-alert" role="status">This order has been cancelled.</p>}<ol className="order-timeline" aria-label="Order progress">{steps.map(([status, label], index) => <li className={currentIndex >= index ? "complete" : ""} aria-current={currentIndex === index ? "step" : undefined} key={status}><span>{index + 1}</span><b>{label}</b></li>)}</ol><p>{process.env.EXPECTED_DELIVERY_MESSAGE || "Expected delivery in 3-7 business days after dispatch."}</p><section><h2>Order details</h2>{order.order_items.map((i: any, n: number) => <p key={n}>{i.product_name} · {i.weight} × {i.quantity} · ₹{i.unit_price} each <b>₹{i.line_total}</b></p>)}<p>Subtotal ₹{order.subtotal}</p><p>Shipping ₹{order.shipping}</p><p>Discount ₹{order.discount}</p><p><strong>Total ₹{order.total}</strong></p></section>{a && <section><h2>Delivering to</h2><p>{a.line1}<br />{a.line2}<br />{a.city}, {a.state} - {a.postal_code}<br />{a.country}</p></section>}<section><h2>Need help?</h2><p>Contact customer support at <a href={`mailto:${support}`}>{support}</a>.</p></section><div className="confirmation-actions"><a className="add-cart" href={invoiceUrl}>Download invoice</a><Link className="add-cart" href="/shop">Continue shopping</Link></div></main>;
}
