"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { Heart, Minus, Plus, Search, ShoppingBag, Trash2, X } from "lucide-react";
import { useCart } from "./cart-provider";
import type { Product } from "../lib/products";
import { PublicLogo } from "./ui/public-logo";
import { GrandmotherIllustration } from "./ui/grandmother-illustration";

export function StoreNav(){const {count}=useCart();return <nav className="store-nav"><PublicLogo className="brand store-logo" imageClassName="store-logo-image"/><div><Link href="/shop">Shop</Link><Link href="/recipes">Recipes</Link><Link href="/about">Our story</Link><Link href="/contact">Contact</Link></div><Link className="cart-link" href="/cart" aria-label="Cart"><ShoppingBag size={18}/>{count>0&&<b>{count}</b>}</Link></nav>}
export function ProductTile({product,selectedWeight="All"}:{product:Product;selectedWeight?:string}){const {add}=useCart();const [wish,setWish]=useState(false);const displayedVariant=selectedWeight==="All"?product.variants[0]:product.variants.find(variant=>variant.weight===selectedWeight)??product.variants[0];if(!displayedVariant)return null;return <article className="store-product"><button className="wish" onClick={()=>setWish(!wish)} aria-label="Save to wishlist"><Heart size={16} fill={wish?"currentColor":"none"}/></button><Link href={`/product/${product.slug}`} className="pack pack-link" style={{background:product.color}}><GrandmotherIllustration color={product.color}/><div className="pack-content">{product.image&&<img className="pack-image" src={product.image} alt=""/>}<b>{product.name}</b><i>Just Like Paati Made It</i></div></Link><div className="product-copy"><p>{product.category.name}</p><h3>{product.name}</h3><div><strong>₹{displayedVariant.price}</strong><span>{displayedVariant.weight}</span></div>{product.variants.length>1&&<p className="variant-weights" aria-label="Available weights">Available: {product.variants.map(variant=>variant.weight).join(" · ")}</p>}<button disabled={displayedVariant.stock===0} className="quick-add" onClick={()=>add(product,displayedVariant.weight)}> {displayedVariant.stock===0?"Out of stock":"Quick add"} <b>+</b></button></div></article>}
export function ShopClient({products}:{products:Product[]}){const [query,setQuery]=useState("");const [category,setCategory]=useState("All");const [weight,setWeight]=useState("All");const [sort,setSort]=useState("popular");const [page,setPage]=useState(1);const perPage=8;
 const filtered=useMemo(()=>products.filter(p=>(category==="All"||p.category.name===category)&&(weight==="All"||p.variants.some(v=>v.weight===weight))&&p.name.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==="name"?a.name.localeCompare(b.name):sort==="price"?(a.variants[0]?.price||0)-(b.variants[0]?.price||0):sort==="newest"?b.id.localeCompare(a.id):0),[products,query,category,weight,sort]);const visible=filtered.slice((page-1)*perPage,page*perPage);const pages=Math.max(1,Math.ceil(filtered.length/perPage));
 return <><StoreNav/><main className="store-page"><p className="eyebrow">THE SARA PANTRY</p><h1>Freshly ground,<br/><em>made with memory.</em></h1><div className="shop-tools"><label><Search size={16}/><input value={query} onChange={e=>{setQuery(e.target.value);setPage(1)}} placeholder="Search the pantry"/></label><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1)}}><option>All</option><option>Spice Powders</option><option>Masalas</option><option>Traditional Podi</option></select><select value={weight} onChange={e=>{setWeight(e.target.value);setPage(1)}}><option>All</option><option>100g</option><option>125g</option><option>150g</option><option>250g</option><option>500g</option></select><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Popularity</option><option value="newest">Newest</option><option value="name">Name</option><option value="price">Price</option></select></div><p className="results">{filtered.length} blends in the Sara pantry</p><div className="product-grid store-grid">{visible.map(p=><ProductTile product={p} selectedWeight={weight} key={p.slug}/>)}</div><div className="pagination">{Array.from({length:pages},(_,i)=><button aria-label={`Page ${i+1}`} className={page===i+1?"active":""} onClick={()=>setPage(i+1)} key={i}>{i+1}</button>)}</div></main></>}
export function ProductDetail({product,relatedProducts}:{product:Product;relatedProducts:Product[]}){const {add}=useCart();const [weight,setWeight]=useState(product.variants[0]?.weight||"");const [qty,setQty]=useState(1);const selected=product.variants.find(v=>v.weight===weight);const price=selected?.price||0;return <><StoreNav/><main className="detail"><p className="crumb"><Link href="/shop">Shop</Link> / {product.category.name} / {product.name}</p><div className="detail-grid"><div className="detail-pack" style={{background:product.color}}><GrandmotherIllustration color={product.color} className="detail-grandmother"/><div className="detail-pack-content">{product.image?<img className="detail-product-image" src={product.image} alt={product.name}/>:<PublicLogo linked={false} imageClassName="detail-logo"/>}<b>{product.name}</b><i>Just Like Paati Made It</i></div></div><div><p className="eyebrow">{product.category.name}</p><h1>{product.name}</h1><div className="stars">★★★★★ <small>4.9 (28 reviews)</small></div><p className="detail-price">₹{price}</p><p className="detail-copy">{product.description}</p><h4>CHOOSE WEIGHT</h4><div className="choices">{product.variants.map(v=><button className={weight===v.weight?"selected":""} onClick={()=>setWeight(v.weight)} key={v.id}>{v.weight}</button>)}</div><h4>QUANTITY</h4><div className="quantity"><button onClick={()=>setQty(Math.max(1,qty-1))}><Minus size={15}/></button><span>{qty}</span><button onClick={()=>setQty(qty+1)}><Plus size={15}/></button></div><button disabled={!selected||selected.stock===0} className="add-cart" onClick={()=>selected&&add(product,weight,qty)}>{selected?.stock===0?"Out of stock":`Add to cart · ₹${price*qty}`}</button><button className="buy-now">Buy now</button><details open><summary>Ingredients</summary><p>{product.ingredients}</p></details><details><summary>Storage & shipping</summary><p>{product.storage}</p></details></div></div>{relatedProducts.length>0&&<section className="related"><p className="eyebrow">YOU MAY ALSO LIKE</p><h2>More from the Sara pantry</h2><div className="product-grid store-grid">{relatedProducts.map(item=><ProductTile key={item.id} product={item}/>)}</div></section>}</main></>}
export function CartPage(){const {items,total,update,remove}=useCart();return <><StoreNav/><main className="cart-page"><p className="eyebrow">YOUR PANTRY</p><h1>Your cart</h1>{items.length===0?<div className="empty"><ShoppingBag/><h2>Your cart is waiting for a little flavour.</h2><Link className="add-cart" href="/shop">Explore the pantry</Link></div>:<div className="cart-layout"><div>{items.map(i=><article className="cart-row" key={i.product.slug+i.weight}><div className="mini-pack" style={{background:i.product.color}}>{i.product.name}</div><div><h3>{i.product.name}</h3><p>{i.weight} · ₹{i.price}</p><div className="quantity"><button onClick={()=>update(i.product.slug,i.weight,i.quantity-1)}><Minus size={14}/></button><span>{i.quantity}</span><button onClick={()=>update(i.product.slug,i.weight,i.quantity+1)}><Plus size={14}/></button></div></div><button className="remove" onClick={()=>remove(i.product.slug,i.weight)}><Trash2 size={17}/></button></article>)}</div><aside className="summary"><h2>Order summary</h2><p><span>Subtotal</span><b>₹{total}</b></p><p><span>Estimated shipping</span><b>Free</b></p><label>COUPON<input placeholder="Enter code"/></label><Link href="/checkout" className="add-cart">Proceed to checkout</Link><Link href="/shop">Continue shopping</Link></aside></div>}</main></>}
