"use client";
import { zodResolver } from "@hookform/resolvers/zod";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useFieldArray, useForm } from "react-hook-form";
import { productSchema, variantSchema } from "../../lib/validations";
import { z } from "zod";
const schema=z.object({product:productSchema,variants:z.array(variantSchema.extend({id:z.string().optional()})).min(1)});type Values=z.infer<typeof schema>;type Category={id:string;name:string};
export function ProductForm({categories,initial}:{categories:Category[];initial?:any}){const router=useRouter();const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const form=useForm<Values>({resolver:zodResolver(schema),defaultValues:{product:{name:initial?.name||"",slug:initial?.slug||"",description:initial?.description||"",ingredients:initial?.ingredients||"",storage:initial?.storage||"Store airtight in a cool, dry place.",category_id:initial?.category_id||categories[0]?.id||"",image:initial?.image||null,featured:initial?.featured||false,best_seller:initial?.best_seller||false},variants:initial?.product_variants?.map((v:any)=>({id:v.id,weight:v.weight,price:v.price,stock:v.stock,sku:v.sku,active:v.active}))||[{weight:"125g",price:90,stock:20,sku:"",active:true}]} });const {fields,append,remove}=useFieldArray({control:form.control,name:"variants"});
 async function upload(file:File){const data=new FormData();data.append("file",file);const response=await fetch("/api/uploads/product-image",{method:"POST",body:data});const json=await response.json();if(!response.ok)throw new Error(json.error);form.setValue("product.image",json.url);}
 async function submit(values:Values){setSaving(true);setMessage("");try{let id=initial?.id;if(!id){const r=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(values)});const j=await r.json();if(!r.ok)throw new Error(j.error);id=j.id;}else{const r=await fetch(`/api/products/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(values.product)});if(!r.ok)throw new Error("Unable to save product.");for(const variant of values.variants){const r=await fetch(variant.id?`/api/product-variants/${variant.id}`:"/api/product-variants",{method:variant.id?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(variant.id?variant:{product_id:id,variant})});if(!r.ok)throw new Error("Unable to save variants.");}}router.push("/admin/products");router.refresh();}catch{setMessage("We could not save this product. Please review the details and try again.");}finally{setSaving(false)}}
 async function deleteVariant(id:string,index:number){if(!confirm("Delete this variant?"))return;const r=await fetch(`/api/product-variants/${id}`,{method:"DELETE"});if(r.ok)remove(index);else setMessage("Unable to delete this variant.")}
 async function deleteProduct(){if(!initial?.id||!confirm("Delete this product and all its variants?"))return;const r=await fetch(`/api/products/${initial.id}`,{method:"DELETE"});if(r.ok){router.push("/admin/products");router.refresh()}else setMessage("Unable to delete this product.")}
 return <form className="admin-form" onSubmit={form.handleSubmit(submit)}><section><h2>Product details</h2><input placeholder="Product name" {...form.register("product.name")}/><input placeholder="Slug" {...form.register("product.slug")}/><select {...form.register("product.category_id")}>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select><textarea placeholder="Description" {...form.register("product.description")}/><textarea placeholder="Ingredients" {...form.register("product.ingredients")}/><textarea placeholder="Storage instructions" {...form.register("product.storage")}/><label>Product image<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0]).catch(()=>setMessage("Image upload failed. Please try again."))}/></label>{form.watch("product.image")&&<img className="admin-image" src={form.watch("product.image")||""} alt="Product preview"/>}<label><input type="checkbox" {...form.register("product.featured")}/> Featured product</label><label><input type="checkbox" {...form.register("product.best_seller")}/> Best seller</label></section><section><h2>Weight variants</h2>{fields.map((field,index)=><div className="variant-row" key={field.id}><input placeholder="Weight" {...form.register(`variants.${index}.weight`)}/><input type="number" placeholder="Price" {...form.register(`variants.${index}.price`)}/><input type="number" placeholder="Stock" {...form.register(`variants.${index}.stock`)}/><input placeholder="SKU" {...form.register(`variants.${index}.sku`)}/><button type="button" onClick={()=>field.id&&initial?.product_variants?.[index]?.id?deleteVariant(initial.product_variants[index].id,index):remove(index)}>Remove</button></div>)}<button type="button" className="secondary admin-add" onClick={()=>append({weight:"",price:0,stock:0,sku:"",active:true})}>Add variant</button></section>{message&&<p role="alert">{message}</p>}<button className="add-cart" disabled={saving}>{saving?"Saving…":"Save changes"}</button>{initial&&<button type="button" className="admin-delete" onClick={deleteProduct}>Delete product</button>}</form>}
