create extension if not exists pgcrypto;

create table public.categories (id uuid primary key default gen_random_uuid(), name text not null, slug text unique not null, image text, created_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), category_id uuid not null references public.categories(id), name text not null, slug text unique not null, description text not null, ingredients text not null, storage text default 'Store airtight in a cool, dry place.', featured boolean not null default false, best_seller boolean not null default false, image text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_variants (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, weight text not null, price numeric(10,2) not null check(price>=0), stock integer not null default 0 check(stock>=0), sku text unique not null, active boolean not null default true);
create table public.customers (id uuid primary key references auth.users(id) on delete cascade, name text, email text unique, phone text, created_at timestamptz not null default now());
create table public.addresses (id uuid primary key default gen_random_uuid(), customer_id uuid not null references public.customers(id) on delete cascade, address text not null, city text not null, state text not null, country text not null default 'India', postal_code text not null, "default" boolean not null default false);
create table public.orders (id uuid primary key default gen_random_uuid(), customer_id uuid references public.customers(id), status text not null default 'pending' check(status in ('pending','packed','shipped','delivered','cancelled')), subtotal numeric(10,2) not null, shipping numeric(10,2) not null default 0, discount numeric(10,2) not null default 0, total numeric(10,2) not null, payment_status text not null default 'pending', payment_method text not null default 'cod', created_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, variant_id uuid not null references public.product_variants(id), quantity integer not null check(quantity>0), price numeric(10,2) not null);

alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_variants enable row level security; alter table public.customers enable row level security; alter table public.addresses enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security;
create policy "Public catalog read" on public.categories for select using (true); create policy "Public product read" on public.products for select using (true); create policy "Public variant read" on public.product_variants for select using (active=true); create policy "Customer owns profile" on public.customers for all using (auth.uid()=id) with check (auth.uid()=id); create policy "Customer owns addresses" on public.addresses for all using (auth.uid()=customer_id) with check (auth.uid()=customer_id); create policy "Customer owns orders" on public.orders for select using (auth.uid()=customer_id); create policy "Customer reads order items" on public.order_items for select using (exists(select 1 from public.orders where orders.id=order_items.order_id and orders.customer_id=auth.uid()));

create or replace function public.fulfil_order_items() returns trigger language plpgsql security definer as $$ begin update public.product_variants set stock=stock-new.quantity where id=new.variant_id and stock>=new.quantity; if not found then raise exception 'Insufficient stock'; end if; return new; end; $$;
create trigger reduce_inventory after insert on public.order_items for each row execute procedure public.fulfil_order_items();
create or replace function public.touch_product() returns trigger language plpgsql as $$ begin new.updated_at=now(); return new; end; $$;
create trigger product_updated before update on public.products for each row execute procedure public.touch_product();

insert into storage.buckets (id,name,public) values ('product-images','product-images',true) on conflict do nothing;
create policy "Public product images" on storage.objects for select using (bucket_id='product-images');
-- Service-role API performs uploads; no browser upload policy is granted.

insert into public.categories(name,slug) values ('Spice Powders','spice-powders'),('Masalas','masalas'),('Traditional Podi','traditional-podi') on conflict do nothing;
with seed(name,category,weights) as (values
('Turmeric Powder','spice-powders',array['125g','250g','500g']),('Dhaniya Powder','spice-powders',array['125g','250g','500g']),('Red Chilli Powder','spice-powders',array['150g','250g','500g']),('Kashmiri Chilli Powder','spice-powders',array['100g','250g','500g']),('Soup Powder','masalas',array['125g','250g','500g']),('Chettinad Chicken Masala','masalas',array['125g','250g','500g']),('Chettinad Paneer Masala','masalas',array['125g','250g','500g']),('Chettinad Mushroom Masala','masalas',array['125g','250g','500g']),('Kurma Powder','masalas',array['100g','250g','500g']),('Spice Powder','masalas',array['125g','250g','500g']),('Mutton Powder','masalas',array['125g','250g','500g']),('Sambar Powder','masalas',array['125g','250g','500g']),('Rasam Powder','masalas',array['125g','250g','500g']),('Idli Podi','traditional-podi',array['150g']),('Chutney Podi','traditional-podi',array['150g']),('Paruppu Podi','traditional-podi',array['150g']),('Curry Leaves Podi','traditional-podi',array['150g']),('Moringa Leaves Podi','traditional-podi',array['150g']),('Chettinad Chukka Powder','masalas',array['150g']))
insert into public.products(category_id,name,slug,description,ingredients) select c.id,s.name,lower(regexp_replace(s.name,'[^a-z0-9]+','-','g')),'Freshly ground in small batches.','Whole spices and herbs. No artificial colours or preservatives.' from seed s join public.categories c on c.slug=s.category on conflict(slug) do nothing;
insert into public.product_variants(product_id,weight,price,stock,sku) select p.id,w,case when w='500g' then 230 when w='250g' then 150 else 90 end,30,upper(replace(p.slug,'-',''))||'-'||upper(w) from public.products p cross join unnest(case when p.name in ('Idli Podi','Chutney Podi','Paruppu Podi','Curry Leaves Podi','Moringa Leaves Podi','Chettinad Chukka Powder') then array['150g'] else array['125g','250g','500g'] end) w on conflict(sku) do nothing;
